version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-banquito
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: villegas-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/banquito
volumes:
  mongo_data: 